# https://support.crowdin.com/developer/configuration-file/
project_identifier: PROJECT_IDENTIFIER_CROWDIN
pull_request_title: New Crowdin updates  # Do not change this line
pull_request_labels:
  - do-not-merge  # Do not change this line
api_key: API_KEY_CROWDIN
base_path: ./
preserve_hierarchy: true
files:
  # Update this to the correct extensions of your project
  - source: /web/pandas/content/en/index.html
    translation: /web/pandas/content/%two_letters_code%/%original_file_name%
    update_option: "update_as_unapproved"
  - source: /web/pandas/content/en/config.yml
    translation: /web/pandas/content/%two_letters_code%/%original_file_name%
    update_option: "update_as_unapproved"
  - source: /web/pandas/content/en/*.md
    translation: /web/pandas/content/%two_letters_code%/%original_file_name%
    update_option: "update_as_unapproved"
  - source: /web/pandas/content/en/about/*.md
    translation: /web/pandas/content/%two_letters_code%/about/%original_file_name%
    update_option: "update_as_unapproved"
  - source: /web/pandas/content/en/community/*.md
    translation: /web/pandas/content/%two_letters_code%/community/%original_file_name%
    update_option: "update_as_unapproved"
